# Generated by Django 5.1.8 on 2025-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stylist",
            name="portfolio",
        ),
        migrations.AddField(
            model_name="service",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
