# Generated by Django 5.1.8 on 2025-04-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon", "0002_remove_stylist_portfolio_service_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="service_pics/"),
        ),
    ]
